# Generated by Django 2.1.2 on 2019-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_demographic'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcode',
            name='local_authority_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='postcode',
            name='local_authority_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
