# Generated by Django 2.1.2 on 2019-02-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20190217_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demographic',
            old_name='borough',
            new_name='local_authority_name',
        ),
        migrations.AddField(
            model_name='demographic',
            name='local_authority_code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
