# Generated by Django 2.1.2 on 2019-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HereMaps', '0003_auto_20190210_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecache',
            name='commute_time',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
