# Generated by Django 2.1.2 on 2019-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HereMaps', '0004_routecache_commute_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routecache',
            name='commute_time',
            field=models.IntegerField(),
        ),
    ]
