# Generated by Django 2.1.2 on 2018-12-12 19:41

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('listing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('displayable_address', models.CharField(max_length=100)),
                ('num_bathrooms', models.IntegerField()),
                ('num_bedrooms', models.IntegerField()),
                ('num_floors', models.IntegerField()),
                ('num_recepts', models.IntegerField()),
                ('listing_status', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('first_published', models.DateTimeField()),
                ('last_published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ZooplaQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('area', models.CharField(max_length=100)),
                ('listing_status', models.CharField(max_length=10)),
                ('radius', models.FloatField()),
                ('minimum_price', models.FloatField(null=True)),
                ('maximum_price', models.FloatField(null=True)),
                ('property_type', models.CharField(max_length=20)),
                ('page', models.IntegerField(default=1)),
                ('number_of_results', models.IntegerField()),
                ('results', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='property',
            name='zoopla_query',
            field=models.ManyToManyField(to='Zoopla.ZooplaQuery'),
        ),
    ]
