# Generated by Django 2.1.2 on 2018-12-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_address', models.CharField(max_length=200)),
                ('agent_logo', models.URLField()),
                ('agent_name', models.CharField(max_length=200)),
                ('agent_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
