# Generated by Django 2.1.2 on 2018-12-12 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0002_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Zoopla.Agent'),
            preserve_default=False,
        ),
    ]
