# Generated by Django 2.1.2 on 2018-12-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0004_auto_20181213_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
    ]
