# Generated by Django 2.1.2 on 2018-12-13 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0005_auto_20181213_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricehistory',
            old_name='percentage',
            new_name='percent',
        ),
    ]
