# Generated by Django 2.1.2 on 2018-12-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0006_auto_20181213_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='county',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
