# Generated by Django 2.1.2 on 2018-12-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0008_auto_20181213_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
