# Generated by Django 2.1.2 on 2018-12-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0009_auto_20181213_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='street_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
