# Generated by Django 2.1.2 on 2018-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0010_auto_20181213_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='short_description',
            field=models.TextField(null=True),
        ),
    ]
