# Generated by Django 2.1.2 on 2018-12-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0011_auto_20181213_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='direction',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
