# Generated by Django 2.1.2 on 2018-12-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0012_auto_20181213_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_logo',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='details_url',
            field=models.URLField(null=True),
        ),
    ]
