# Generated by Django 2.1.2 on 2018-12-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zoopla', '0014_rentalprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
