# Generated by Django 2.1.2 on 2019-02-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='locality',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='town',
            field=models.CharField(max_length=60),
        ),
    ]
