# Generated by Django 2.1.2 on 2019-02-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0002_auto_20190203_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='religion',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='selective',
            field=models.BooleanField(null=True),
        ),
    ]
