# Generated by Django 2.1.2 on 2019-02-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0003_auto_20190205_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='religion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
