# Generated by Django 2.1.2 on 2019-02-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0004_auto_20190205_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='town',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
