# Generated by Django 2.1.2 on 2019-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0005_auto_20190213_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
    ]
