# Generated by Django 2.1.2 on 2019-02-23 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivePlace',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100, null=True)),
                ('locality', models.CharField(max_length=60, null=True)),
                ('town', models.CharField(max_length=60, null=True)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('active_place_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=30)),
                ('kind', models.CharField(max_length=30)),
                ('outputAreaCode', models.CharField(max_length=30)),
                ('lowerSuperOutputArea', models.CharField(max_length=30)),
                ('middleSuperOutputArea', models.CharField(max_length=30)),
                ('parliamentaryConstituencyCode', models.CharField(max_length=30)),
                ('parliamentaryConstituencyName', models.CharField(max_length=60)),
                ('wardCode', models.CharField(max_length=30)),
                ('wardName', models.CharField(max_length=60)),
                ('localAuthorityCode', models.CharField(max_length=30)),
                ('localAuthorityName', models.CharField(max_length=60)),
                ('buildingName', models.CharField(max_length=100)),
                ('buildingNumber', models.CharField(max_length=20)),
                ('hasCarPark', models.BooleanField(default=False)),
                ('carParkCapacity', models.IntegerField()),
                ('dedicatedFootballFacility', models.BooleanField(default=False)),
                ('cyclePark', models.BooleanField(default=False)),
                ('cycleHire', models.BooleanField(default=False)),
                ('cycleRepairWorkshop', models.BooleanField(default=False)),
                ('nursery', models.BooleanField(default=False)),
                ('ownerType', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactType', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=30)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField()),
                ('notes', models.CharField(max_length=200, null=True)),
                ('parking', models.BooleanField()),
                ('findingReachingEntrance', models.BooleanField()),
                ('receptionArea', models.BooleanField()),
                ('doorways', models.BooleanField()),
                ('changingFacilities', models.BooleanField()),
                ('activityAreas', models.BooleanField()),
                ('toilets', models.BooleanField()),
                ('socialAreas', models.BooleanField()),
                ('spectatorAreas', models.BooleanField()),
                ('emergencyExits', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableTennisTables', models.BooleanField(default=False)),
                ('poolHoist', models.BooleanField(default=False)),
                ('bowlingMachine', models.BooleanField(default=False)),
                ('trampolines', models.BooleanField(default=False)),
                ('parallelBars', models.BooleanField(default=False)),
                ('highBars', models.BooleanField(default=False)),
                ('stillRings', models.BooleanField(default=False)),
                ('unevenBars', models.BooleanField(default=False)),
                ('balanceBeam', models.BooleanField(default=False)),
                ('vault', models.BooleanField(default=False)),
                ('pommelHorse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilityType', models.CharField(max_length=30)),
                ('yearBuilt', models.IntegerField()),
                ('yearBuiltEstimated', models.BooleanField(default=False)),
                ('isRefurbished', models.BooleanField(default=False)),
                ('yearRefurbished', models.IntegerField()),
                ('hasChangingRooms', models.BooleanField()),
                ('areChangingRoomsRefurbished', models.BooleanField()),
                ('yearChangingRoomsRefurbished', models.IntegerField()),
                ('seasonalityType', models.CharField(max_length=30)),
                ('seasonalityStart', models.CharField(max_length=30)),
                ('seasonalityEnd', models.CharField(max_length=30)),
                ('active_place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ActivePlaces.ActivePlace')),
            ],
        ),
        migrations.CreateModel(
            name='OpeningTimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessDescription', models.CharField(max_length=100)),
                ('openingTime', models.CharField(max_length=20)),
                ('closingTime', models.CharField(max_length=20)),
                ('periodOpenFor', models.CharField(max_length=50)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ActivePlaces.Facility')),
            ],
        ),
        migrations.AddField(
            model_name='activeplace',
            name='disability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ActivePlaces.Disability'),
        ),
        migrations.AddField(
            model_name='activeplace',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='ActivePlaces.Equipment'),
        ),
    ]
