# Generated by Django 2.1.2 on 2019-02-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0003_activeplace_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telephone',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
