# Generated by Django 2.1.2 on 2019-02-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0005_auto_20190224_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disability',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
