# Generated by Django 2.1.2 on 2019-02-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0006_auto_20190224_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='website',
            field=models.URLField(max_length=400, null=True),
        ),
    ]
