# Generated by Django 2.1.2 on 2019-02-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0007_auto_20190224_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='telephone',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
