# Generated by Django 2.1.2 on 2019-02-24 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0008_auto_20190224_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeplace',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ActivePlaces.Contacts'),
        ),
    ]
