# Generated by Django 2.1.2 on 2019-02-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0009_auto_20190224_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeplace',
            name='buildingName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
