# Generated by Django 2.1.2 on 2019-02-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0010_auto_20190224_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeplace',
            name='ownerType',
            field=models.CharField(max_length=60),
        ),
    ]
