# Generated by Django 2.1.2 on 2019-02-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0011_auto_20190224_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeplace',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ActivePlaces.Contacts'),
        ),
        migrations.AlterField(
            model_name='activeplace',
            name='disability',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ActivePlaces.Disability'),
        ),
        migrations.AlterField(
            model_name='activeplace',
            name='equipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ActivePlaces.Equipment'),
        ),
    ]
