# Generated by Django 2.1.2 on 2019-02-24 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0012_auto_20190224_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeplace',
            name='activities',
            field=models.ManyToManyField(to='ActivePlaces.Activity'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='active_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActivePlaces.ActivePlace'),
        ),
    ]
