# Generated by Django 2.1.2 on 2019-02-24 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ActivePlaces', '0013_auto_20190224_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='areChangingRoomsRefurbished',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='hasChangingRooms',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='yearBuilt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='yearChangingRoomsRefurbished',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='yearRefurbished',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='openingtimes',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ActivePlaces.Facility'),
        ),
    ]
