# Generated by Django 2.1.2 on 2019-02-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQC', '0004_auto_20190213_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cqclocation',
            name='postcode',
            field=models.CharField(max_length=10),
        ),
    ]
