# Generated by Django 2.1.2 on 2019-02-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CQC', '0006_auto_20190213_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='cqclocation',
            name='overall_rating',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
